overrides:
  '@modelcontextprotocol/sdk@<1.24.0': '>=1.24.0'
  '@modelcontextprotocol/sdk@<1.25.2': '>=1.25.2'
  '@modelcontextprotocol/sdk@>=1.10.0 <=1.25.3': '>=1.26.0'
  agents@<0.3.10: '>=0.3.10'
  agents@<0.3.7: '>=0.3.7'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  qs@<6.14.1: '>=6.14.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  undici@>=7.0.0 <7.18.2: '>=7.18.2'
  wrangler@>=4.0.0 <4.59.1: '>=4.59.1'
